version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb_store:/app/chromadb_store
    working_dir: /app
    command:  ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]





  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    expose:
      - "7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    ports:
      - "7860:7860"
    #extra hosts can be used for standalone SQL Server or services at the dev PC
    volumes:
      - ./FinanceFrontend:/app/
    working_dir: /app
    depends_on:
      - backend
    command: ["gradio", "main.py"]
