FROM python:3.9-slim
# Python docker images: https://github.com/docker-library/docs/tree/master/python/

USER root


COPY FinanceFrontend/requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 7860
# EXPOSE 
